export const GET_SONGS_ID_START = "GET_SONGS_ID_START";
export const GET_SONGS_ID = "GET_SONGS_ID";
export const GET_SONGS_ID_SUCCESS = "GET_SONGS_ID_SUCCESS";
export const GET_SONGS_ID_FAIL = "GET_SONGS_ID_FAIL";

export const ADD_SONGS_ID_START = "ADD_SONGS_ID_START";
export const ADD_SONGS_ID = "ADD_SONGS_ID";
export const ADD_SONGS_ID_SUCCESS = "ADD_SONGS_ID_SUCCESS";
export const ADD_SONGS_ID_FAIL = "ADD_SONGS_ID_FAIL";